version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  database:
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: estacionamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload
      - ./backend/src:/app/src:ro
      - ./backend/package.json:/app/package.json:ro
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./angular.json:/app/angular.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./tsconfig.app.json:/app/tsconfig.app.json:ro
      - ./package.json:/app/package.json:ro
    ports:
      - "4200:4200"
    command: npm start -- --host 0.0.0.0 --poll 2000
